# Generated by Django 2.1 on 2019-03-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Functions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(max_length=30)),
                ('function_date', models.DateField()),
                ('function_cost', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FunctionTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_type', models.CharField(max_length=30)),
            ],
        ),
    ]
