# Generated by Django 2.1 on 2019-03-15 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mahal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masjid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masjid_name', models.CharField(max_length=100)),
                ('masjid_address', models.TextField(max_length=400)),
                ('masjid_contact_no', models.CharField(max_length=15)),
                ('masjid_email', models.CharField(max_length=50)),
                ('mahal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mahal.Mahal')),
            ],
        ),
    ]
