# Generated by Django 2.1 on 2019-03-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahal_name', models.CharField(max_length=100)),
                ('mahal_address', models.TextField(max_length=400)),
                ('mahal_contact_no', models.CharField(max_length=15)),
                ('mahal_email', models.CharField(max_length=100)),
                ('mahal_wakaf_no', models.CharField(max_length=20)),
            ],
        ),
    ]
