# Generated by Django 2.1 on 2019-03-15 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100)),
                ('member_address', models.TextField(max_length=400)),
                ('member_contact_no', models.CharField(max_length=15)),
                ('member_dob', models.DateField()),
                ('member_email', models.CharField(max_length=50)),
                ('memeber_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Family')),
            ],
        ),
    ]
