# Generated by Django 2.1 on 2019-03-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('school_address', models.TextField(max_length=400)),
                ('school_contact_no', models.CharField(max_length=15)),
                ('school_email', models.CharField(max_length=50)),
            ],
        ),
    ]
